### PR TITLE
Convert makefile release process to an automated workflow

### LINKED ISSUE #15: Migrate release process to GitHub Actions
Looking at canned github actions for more and more of our workflows, I think that these two actions provide most of the functionality that we currently have in the Makefile:

- https://github.com/marketplace/actions/create-a-release
- https://github.com/marketplace/actions/upload-a-release-asset

The things I see that may be missing right now are:

- *The ability to upload a whole directory of binaries.* I would rather not have to maintain a unique config for every binary we upload. This would require updating multiple configs to add new binaries. So far the only examples I've seen working do one at a time, such as https://github.com/tylerauerbeck/dash/blob/master/.github/workflows/release.yml#L35-L74
- *The ability to use `git log` to generate my release body text.* From what I understand, the create-release plugin doesn't pull the whole git tree, so the log isn't possible in that context.

### PR DESCRIPTION
**Pull request by etsauer**
@cpitman @sabre1041 resolves #15

### CODE REVIEW

**Comment by cpitman** [comment]
Is there somewhere this was tested? Or is the only way to test it to merge and run?

**Review by sabre1041 — CHANGES_REQUESTED** [review]
@etsauer received an error while testing: https://github.com/sabre1041/template2helm/runs/438251150?check_suite_focus=true

**Comment by etsauer** [comment]
@sabre1041 strange. This seems like its unrelated to the PR. can you try re-running that build?

**Review by cpitman — APPROVED** [review]
LGTM, after reviewing releases on Eric's fork

**Review by sabre1041 — APPROVED** [review]
LGTM Great work @etsauer

**Pull request merged**
